// Generated by npm run build.
const CACHE_NAME = 'ink-battle-2-8c21afc417b0de8a';
const APP_SHELL = [
  "./",
  "./index.html",
  "./ink-battle.html",
  "./mr.html",
  "./src/mr/tabletop.css",
  "./web/mr.js",
  "./web/THREE-LICENSE.txt",
  "./privacy-policy.html",
  "./manifest.webmanifest",
  "./favicon.ico",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/fonts/caveat.ttf",
  "./assets/fonts/patrick-hand.ttf",
  "./src/client/game.css",
  "./web/game.js",
  "./web/gemma-worker.js"
];
/* global CACHE_NAME, APP_SHELL */
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(APP_SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key.startsWith('ink-battle-') && key !== CACHE_NAME).map(key => caches.delete(key)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;
  // Music streams independently; the game, art, controls and fonts are fully cached.
  if (url.pathname.includes('/assets/audio/')) return;
  const shell = APP_SHELL.some(path => new URL(path, self.registration.scope).pathname === url.pathname);
  if (!shell) return;
  event.respondWith(caches.open(CACHE_NAME).then(async cache => {
    const cached = await cache.match(new Request(url.origin + url.pathname));
    return cached || fetch(event.request);
  }));
});
