import { build } from 'esbuild';
import { mkdir, writeFile, readFile, copyFile, chmod } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { RUNTIME_VERSION } from '../src/client/gemma-web-config.js';
await mkdir('web', { recursive: true });
await build({ entryPoints: ['src/client/app.js'], bundle: true, outfile: 'web/game.js', format: 'iife', target: ['es2022'], legalComments: 'inline' });
await build({ entryPoints: ['src/mr/app.js'], bundle: true, outfile: 'web/mr.js', format: 'iife', target: ['es2022'], legalComments: 'inline', minify: true });
await copyFile('node_modules/three/LICENSE', 'web/THREE-LICENSE.txt');
await build({ entryPoints: ['src/client/gemma-worker.js'], bundle: true, outfile: 'web/gemma-worker.js', format: 'iife', target: ['es2022'], legalComments: 'inline' });
const vendor = `web/vendor/litert-lm-${RUNTIME_VERSION}`;
await mkdir(vendor, { recursive: true });
for (const suffix of ['js', 'wasm']) {
  const destination = `${vendor}/litertlm_wasm_compat_internal.${suffix}`;
  await copyFile(`node_modules/@litert-lm/core/wasm/litertlm_wasm_compat_internal.${suffix}`, destination);
  // npm's runtime files are executable on Linux; web assets must have stable modes.
  await chmod(destination, 0o644);
}
const version = JSON.parse(await readFile('package.json', 'utf8')).version;
await writeFile('web/build.json', JSON.stringify({ version, entry: 'game.js' }) + '\n');
const shell = ['./', './index.html', './ink-battle.html', './mr.html', './src/mr/tabletop.css', './web/mr.js', './web/THREE-LICENSE.txt', './privacy-policy.html', './manifest.webmanifest', './favicon.ico',
  './assets/icon-192.png', './assets/icon-512.png', './assets/fonts/caveat.ttf', './assets/fonts/patrick-hand.ttf', './src/client/game.css', './web/game.js', './web/gemma-worker.js'];
const hash = createHash('sha256');
for (const file of shell.filter(f => f !== './')) {
  const data = await readFile(file);
  hash.update(/\.(html|webmanifest|css|js)$/.test(file) ? data.toString('utf8').replace(/\r\n/g, '\n') : data);
}
const revision = hash.digest('hex').slice(0, 16);
const template = await readFile('scripts/service-worker.template.js', 'utf8');
await writeFile('service-worker.js', `// Generated by npm run build.\nconst CACHE_NAME = 'ink-battle-2-${revision}';\nconst APP_SHELL = ${JSON.stringify(shell, null, 2)};\n${template}`);
