import { build } from 'esbuild';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
await mkdir('web', { recursive: true });
await build({ entryPoints: ['src/client/app.js'], bundle: true, outfile: 'web/game.js', format: 'iife', target: ['es2022'], legalComments: 'inline' });
await writeFile('web/build.json', JSON.stringify({ version: '2.0.0', entry: 'game.js' }) + '\n');
const shell = ['./', './index.html', './ink-battle.html', './privacy-policy.html', './manifest.webmanifest', './favicon.ico',
  './assets/icon-192.png', './assets/icon-512.png', './assets/fonts/caveat.ttf', './assets/fonts/patrick-hand.ttf', './src/client/game.css', './web/game.js'];
const hash = createHash('sha256');
for (const file of shell.filter(f => f !== './')) {
  const data = await readFile(file);
  hash.update(/\.(html|webmanifest|css|js)$/.test(file) ? data.toString('utf8').replace(/\r\n/g, '\n') : data);
}
const revision = hash.digest('hex').slice(0, 16);
const template = await readFile('scripts/service-worker.template.js', 'utf8');
await writeFile('service-worker.js', `// Generated by npm run build.\nconst CACHE_NAME = 'ink-battle-2-${revision}';\nconst APP_SHELL = ${JSON.stringify(shell, null, 2)};\n${template}`);
